language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t mlindemann/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true mlindemann/react-test npm test

after_success: 
  - docker build -t mlindemann/multi-client ./client
  - docker build -t mlindemann/multi-nginx ./nginx
  - docker build -t mlindemann/multi-server ./server
  - docker build -t mlindemann/multi-worker ./worker
  # Login docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mlindemann/multi-client
  - docker push mlindemann/multi-nginx
  - docker push mlindemann/multi-server
  - docker push mlindemann/multi-worker
  
